apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: murph-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: datawindtunnel/pipeline-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              value: pipeline
            - name: MARIADB_PASSWORD
              value: "123456"
            - name: MARIADB_ROOT_PASSWORD
              value: "123456"
            - name: MARIADB_USER
              value: local

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: murph-dev
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
