apiVersion: v1
kind: PersistentVolume
metadata:
  name: phase3-pv
  namespace: murph-dev
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
