apiVersion: apps/v1
kind: Deployment
metadata:
  name: phase3-deployment
  namespace: murph-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phase3
  template:
    metadata:
      labels:
        app: phase3
    spec:
      containers:
        - name: phase3
          image: datawindtunnel/phase3-service:murph
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: dummy-volume
              mountPath: /dummy
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: BASE_PATH
              value: "/tmp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "opentelemetrycollector:4317"
            - name: MYSQL_USER
              value: local
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_HOST
              value: mariadb-service
            - name: MYSQL_DATABASE
              value: pipeline
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: dummy-volume
          persistentVolumeClaim: 
            claimName: phase3-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phase3-pv-claim
  namespace: murph-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
